sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t chungisudocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chungisudocker/react-test npm test

after_success:
  - docker build -t chungisudocker/multi-client ./client
  - docker build -t chungisudocker/multi-nginx ./nginx
  - docker build -t chungisudocker/multi-server ./server
  - docker build -t chungisudocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chungisudocker/multi-client
  - docker push chungisudocker/multi-nginx
  - docker push chungisudocker/multi-server
  - docker push chungisudocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'multi-docker-ap-northeast-2-bucket'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
